In [1]:
import pandas as pd

In [2]:
 dt = pd.read_csv("df_batting.csv")
dt

match teamInnings  battingPos             batsmanName  \
0    Namibia Vs Sri Lanka     Namibia           1      Michael van Lingen   
1    Namibia Vs Sri Lanka     Namibia           2           Divan la Cock   
2    Namibia Vs Sri Lanka     Namibia           3  Jan Nicol Loftie-Eaton   
3    Namibia Vs Sri Lanka     Namibia           4           Stephan Baard   
4    Namibia Vs Sri Lanka     Namibia           5      Gerhard Erasmus(c)   
..                    ...         ...         ...                     ...   
694   Pakistan Vs England     England           3               Phil Salt   
695   Pakistan Vs England     England           4              Ben Stokes   
696   Pakistan Vs England     England           5             Harry Brook   
697   Pakistan Vs England     England           6               Moeen Ali   
698   Pakistan Vs England     England           7        Liam Livingstone   

     runs  balls  4s  6s      SR out/not_out     match_id  
0       3      6   0   0   50.00         out  T20I # 1823  
1       9      9   1   0  100.00         out  T20I # 1823  
2      20     12   1   2  166.66         out  T20I # 1823  
3      26     24   2   0  108.33         out  T20I # 1823  
4      20     24   0   0   83.33         out  T20I # 1823  
..    ...    ...  ..  ..     ...         ...          ...  
694    10      9   2   0  111.11         out  T20I # 1879  
695    52     49   5   1  106.12     not_out  T20I # 1879  
696    20     23   1   0   86.95         out  T20I # 1879  
697    19     13   3   0  146.15         out  T20I # 1879  
698     1      1   0   0  100.00     not_out  T20I # 1879  

[699 rows x 11 columns]

In [3]:
data_shape = dt.shape
print("shape of data frame,",data_shape)

shape of data frame, (699, 11)


In [4]:
data_type = dt.dtypes
print("type of data \n",data_type)

type of data 
 match          object
teamInnings    object
battingPos      int64
batsmanName    object
runs            int64
balls           int64
4s              int64
6s              int64
SR             object
out/not_out    object
match_id       object
dtype: object


In [5]:
data_info = dt.info()
print("information for data", data_info)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   match        699 non-null    object
 1   teamInnings  699 non-null    object
 2   battingPos   699 non-null    int64 
 3   batsmanName  699 non-null    object
 4   runs         699 non-null    int64 
 5   balls        699 non-null    int64 
 6   4s           699 non-null    int64 
 7   6s           699 non-null    int64 
 8   SR           699 non-null    object
 9   out/not_out  699 non-null    object
 10  match_id     699 non-null    object
dtypes: int64(5), object(6)
memory usage: 60.2+ KB
information for data None


In [6]:
missing_values = dt.isnull()
print("Missing Values \n", missing_values)

Missing Values 
      match  teamInnings  battingPos  batsmanName   runs  balls     4s     6s  \
0    False        False       False        False  False  False  False  False   
1    False        False       False        False  False  False  False  False   
2    False        False       False        False  False  False  False  False   
3    False        False       False        False  False  False  False  False   
4    False        False       False        False  False  False  False  False   
..     ...          ...         ...          ...    ...    ...    ...    ...   
694  False        False       False        False  False  False  False  False   
695  False        False       False        False  False  False  False  False   
696  False        False       False        False  False  False  False  False   
697  False        False       False        False  False  False  False  False   
698  False        False       False        False  False  False  False  False   

        SR  out/not_ou

In [7]:
missing_values = dt.isnull().sum()
print("Missing Values \n", missing_values)

Missing Values 
 match          0
teamInnings    0
battingPos     0
batsmanName    0
runs           0
balls          0
4s             0
6s             0
SR             0
out/not_out    0
match_id       0
dtype: int64


In [8]:
summary_stats = dt.describe()
summary_stats_all = dt.describe(include='all')
print(summary_stats)
print(summary_stats_all)

       battingPos        runs       balls          4s          6s
count  699.000000  699.000000  699.000000  699.000000  699.000000
mean     4.979971   15.978541   13.648069    1.300429    0.473534
std      2.813628   18.709462   12.718093    1.834448    0.978465
min      1.000000    0.000000    0.000000    0.000000    0.000000
25%      3.000000    2.000000    4.000000    0.000000    0.000000
50%      5.000000    9.000000   10.000000    1.000000    0.000000
75%      7.000000   22.500000   19.000000    2.000000    1.000000
max     11.000000  109.000000   64.000000   10.000000    8.000000
                           match teamInnings  battingPos         batsmanName  \
count                        699         699  699.000000                 699   
unique                        42          16         NaN                 200   
top     Pakistan Vs South Africa    Zimbabwe         NaN  Scott Edwards(c)†  
freq                          21          74         NaN                   8   
mean  

In [9]:
dt

match teamInnings  battingPos             batsmanName  \
0    Namibia Vs Sri Lanka     Namibia           1      Michael van Lingen   
1    Namibia Vs Sri Lanka     Namibia           2           Divan la Cock   
2    Namibia Vs Sri Lanka     Namibia           3  Jan Nicol Loftie-Eaton   
3    Namibia Vs Sri Lanka     Namibia           4           Stephan Baard   
4    Namibia Vs Sri Lanka     Namibia           5      Gerhard Erasmus(c)   
..                    ...         ...         ...                     ...   
694   Pakistan Vs England     England           3               Phil Salt   
695   Pakistan Vs England     England           4              Ben Stokes   
696   Pakistan Vs England     England           5             Harry Brook   
697   Pakistan Vs England     England           6               Moeen Ali   
698   Pakistan Vs England     England           7        Liam Livingstone   

     runs  balls  4s  6s      SR out/not_out     match_id  
0       3      6   0   0   50.00         out  T20I # 1823  
1       9      9   1   0  100.00         out  T20I # 1823  
2      20     12   1   2  166.66         out  T20I # 1823  
3      26     24   2   0  108.33         out  T20I # 1823  
4      20     24   0   0   83.33         out  T20I # 1823  
..    ...    ...  ..  ..     ...         ...          ...  
694    10      9   2   0  111.11         out  T20I # 1879  
695    52     49   5   1  106.12     not_out  T20I # 1879  
696    20     23   1   0   86.95         out  T20I # 1879  
697    19     13   3   0  146.15         out  T20I # 1879  
698     1      1   0   0  100.00     not_out  T20I # 1879  

[699 rows x 11 columns]

In [11]:
dt.head(10)

match teamInnings  battingPos             batsmanName  runs  \
0  Namibia Vs Sri Lanka     Namibia           1      Michael van Lingen     3   
1  Namibia Vs Sri Lanka     Namibia           2           Divan la Cock     9   
2  Namibia Vs Sri Lanka     Namibia           3  Jan Nicol Loftie-Eaton    20   
3  Namibia Vs Sri Lanka     Namibia           4           Stephan Baard    26   
4  Namibia Vs Sri Lanka     Namibia           5      Gerhard Erasmus(c)    20   
5  Namibia Vs Sri Lanka     Namibia           6            Jan Frylinck    44   
6  Namibia Vs Sri Lanka     Namibia           7             David Wiese     0   
7  Namibia Vs Sri Lanka     Namibia           8                 JJ Smit    31   
8  Namibia Vs Sri Lanka   Sri Lanka           1         Pathum Nissanka     9   
9  Namibia Vs Sri Lanka   Sri Lanka           2          Kusal Mendis†    6   

   balls  4s  6s      SR out/not_out     match_id  
0      6   0   0   50.00         out  T20I # 1823  
1      9   1   0  100.00         out  T20I # 1823  
2     12   1   2  166.66         out  T20I # 1823  
3     24   2   0  108.33         out  T20I # 1823  
4     24   0   0   83.33         out  T20I # 1823  
5     28   4   0  157.14         out  T20I # 1823  
6      1   0   0    0.00         out  T20I # 1823  
7     16   2   2  193.75     not_out  T20I # 1823  
8     10   1   0   90.00         out  T20I # 1823  
9      6   0   0  100.00         out  T20I # 1823

In [12]:
dt.loc[4,"batsmanName"]

'Gerhard Erasmus(c)'

In [13]:
dt.loc[[4],["teamInnings","batsmanName","runs","balls"]]

teamInnings         batsmanName  runs  balls
4     Namibia  Gerhard Erasmus(c)    20     24

In [14]:
dt.loc[[4,8],["teamInnings","batsmanName","runs","balls"]]

teamInnings         batsmanName  runs  balls
4     Namibia  Gerhard Erasmus(c)    20     24
8   Sri Lanka     Pathum Nissanka     9     10

In [15]:
dt.iloc[[3,6,1],[1,3,4,5,9,10]]

teamInnings    batsmanName  runs  balls out/not_out     match_id
3     Namibia  Stephan Baard    26     24         out  T20I # 1823
6     Namibia    David Wiese     0      1         out  T20I # 1823
1     Namibia  Divan la Cock     9      9         out  T20I # 1823

In [16]:
dt_1 = pd.read_csv("df_batting.csv",index_col=3)
dt_1

match teamInnings  battingPos  runs  \
batsmanName                                                                  
Michael van Lingen      Namibia Vs Sri Lanka     Namibia           1     3   
Divan la Cock           Namibia Vs Sri Lanka     Namibia           2     9   
Jan Nicol Loftie-Eaton  Namibia Vs Sri Lanka     Namibia           3    20   
Stephan Baard           Namibia Vs Sri Lanka     Namibia           4    26   
Gerhard Erasmus(c)      Namibia Vs Sri Lanka     Namibia           5    20   
...                                      ...         ...         ...   ...   
Phil Salt                Pakistan Vs England     England           3    10   
Ben Stokes               Pakistan Vs England     England           4    52   
Harry Brook              Pakistan Vs England     England           5    20   
Moeen Ali                Pakistan Vs England     England           6    19   
Liam Livingstone         Pakistan Vs England     England           7     1   

                        balls  4s  6s      SR out/not_out     match_id  
batsmanName                                                             
Michael van Lingen          6   0   0   50.00         out  T20I # 1823  
Divan la Cock               9   1   0  100.00         out  T20I # 1823  
Jan Nicol Loftie-Eaton     12   1   2  166.66         out  T20I # 1823  
Stephan Baard              24   2   0  108.33         out  T20I # 1823  
Gerhard Erasmus(c)         24   0   0   83.33         out  T20I # 1823  
...                       ...  ..  ..     ...         ...          ...  
Phil Salt                   9   2   0  111.11         out  T20I # 1879  
Ben Stokes                 49   5   1  106.12     not_out  T20I # 1879  
Harry Brook                23   1   0   86.95         out  T20I # 1879  
Moeen Ali                  13   3   0  146.15         out  T20I # 1879  
Liam Livingstone            1   0   0  100.00     not_out  T20I # 1879  

[699 rows x 10 columns]

In [17]:
dt_1.drop("teamInnings", axis=1, inplace= True)

In [18]:
dt_1

match  battingPos  runs  balls  4s  6s  \
batsmanName                                                                     
Michael van Lingen      Namibia Vs Sri Lanka           1     3      6   0   0   
Divan la Cock           Namibia Vs Sri Lanka           2     9      9   1   0   
Jan Nicol Loftie-Eaton  Namibia Vs Sri Lanka           3    20     12   1   2   
Stephan Baard           Namibia Vs Sri Lanka           4    26     24   2   0   
Gerhard Erasmus(c)      Namibia Vs Sri Lanka           5    20     24   0   0   
...                                      ...         ...   ...    ...  ..  ..   
Phil Salt                Pakistan Vs England           3    10      9   2   0   
Ben Stokes               Pakistan Vs England           4    52     49   5   1   
Harry Brook              Pakistan Vs England           5    20     23   1   0   
Moeen Ali                Pakistan Vs England           6    19     13   3   0   
Liam Livingstone         Pakistan Vs England           7     1      1   0   0   

                            SR out/not_out     match_id  
batsmanName                                              
Michael van Lingen       50.00         out  T20I # 1823  
Divan la Cock           100.00         out  T20I # 1823  
Jan Nicol Loftie-Eaton  166.66         out  T20I # 1823  
Stephan Baard           108.33         out  T20I # 1823  
Gerhard Erasmus(c)       83.33         out  T20I # 1823  
...                        ...         ...          ...  
Phil Salt               111.11         out  T20I # 1879  
Ben Stokes              106.12     not_out  T20I # 1879  
Harry Brook              86.95         out  T20I # 1879  
Moeen Ali               146.15         out  T20I # 1879  
Liam Livingstone        100.00     not_out  T20I # 1879  

[699 rows x 9 columns]

In [24]:
dt_2 = pd.read_csv("df_batting.csv")
dt_2

match teamInnings  battingPos             batsmanName  \
0    Namibia Vs Sri Lanka     Namibia           1      Michael van Lingen   
1    Namibia Vs Sri Lanka     Namibia           2           Divan la Cock   
2    Namibia Vs Sri Lanka     Namibia           3  Jan Nicol Loftie-Eaton   
3    Namibia Vs Sri Lanka     Namibia           4           Stephan Baard   
4    Namibia Vs Sri Lanka     Namibia           5      Gerhard Erasmus(c)   
..                    ...         ...         ...                     ...   
694   Pakistan Vs England     England           3               Phil Salt   
695   Pakistan Vs England     England           4              Ben Stokes   
696   Pakistan Vs England     England           5             Harry Brook   
697   Pakistan Vs England     England           6               Moeen Ali   
698   Pakistan Vs England     England           7        Liam Livingstone   

     runs  balls  4s  6s      SR out/not_out     match_id  
0       3      6   0   0   50.00         out  T20I # 1823  
1       9      9   1   0  100.00         out  T20I # 1823  
2      20     12   1   2  166.66         out  T20I # 1823  
3      26     24   2   0  108.33         out  T20I # 1823  
4      20     24   0   0   83.33         out  T20I # 1823  
..    ...    ...  ..  ..     ...         ...          ...  
694    10      9   2   0  111.11         out  T20I # 1879  
695    52     49   5   1  106.12     not_out  T20I # 1879  
696    20     23   1   0   86.95         out  T20I # 1879  
697    19     13   3   0  146.15         out  T20I # 1879  
698     1      1   0   0  100.00     not_out  T20I # 1879  

[699 rows x 11 columns]

In [26]:
dt_2.loc[1:20,:"balls"]

match teamInnings  battingPos                 batsmanName  \
1    Namibia Vs Sri Lanka     Namibia           2               Divan la Cock   
2    Namibia Vs Sri Lanka     Namibia           3      Jan Nicol Loftie-Eaton   
3    Namibia Vs Sri Lanka     Namibia           4               Stephan Baard   
4    Namibia Vs Sri Lanka     Namibia           5          Gerhard Erasmus(c)   
5    Namibia Vs Sri Lanka     Namibia           6                Jan Frylinck   
6    Namibia Vs Sri Lanka     Namibia           7                 David Wiese   
7    Namibia Vs Sri Lanka     Namibia           8                     JJ Smit   
8    Namibia Vs Sri Lanka   Sri Lanka           1             Pathum Nissanka   
9    Namibia Vs Sri Lanka   Sri Lanka           2              Kusal Mendis†  
10   Namibia Vs Sri Lanka   Sri Lanka           3         Dhananjaya de Silva   
11   Namibia Vs Sri Lanka   Sri Lanka           4        Danushka Gunathilaka   
12   Namibia Vs Sri Lanka   Sri Lanka           5           Bhanuka Rajapaksa   
13   Namibia Vs Sri Lanka   Sri Lanka           6            Dasun Shanaka(c)   
14   Namibia Vs Sri Lanka   Sri Lanka           7  Wanindu Hasaranga de Silva   
15   Namibia Vs Sri Lanka   Sri Lanka           8         Chamika Karunaratne   
16   Namibia Vs Sri Lanka   Sri Lanka           9             Pramod Madushan   
17   Namibia Vs Sri Lanka   Sri Lanka          10         Dushmantha Chameera   
18   Namibia Vs Sri Lanka   Sri Lanka          11          Maheesh Theekshana   
19  U.A.E. Vs Netherlands      U.A.E.           1                 Chirag Suri   
20  U.A.E. Vs Netherlands      U.A.E.           2             Muhammad Waseem   

    runs  balls  
1      9      9  
2     20     12  
3     26     24  
4     20     24  
5     44     28  
6      0      1  
7     31     16  
8      9     10  
9      6      6  
10    12     11  
11     0      1  
12    20     21  
13    29     23  
14     4      8  
15     5      8  
16     0      0  
17     8     15  
18    11     11  
19    12     20  
20    41     47

In [28]:
dt_2.iloc[1:20,:5]

match teamInnings  battingPos                 batsmanName  \
1    Namibia Vs Sri Lanka     Namibia           2               Divan la Cock   
2    Namibia Vs Sri Lanka     Namibia           3      Jan Nicol Loftie-Eaton   
3    Namibia Vs Sri Lanka     Namibia           4               Stephan Baard   
4    Namibia Vs Sri Lanka     Namibia           5          Gerhard Erasmus(c)   
5    Namibia Vs Sri Lanka     Namibia           6                Jan Frylinck   
6    Namibia Vs Sri Lanka     Namibia           7                 David Wiese   
7    Namibia Vs Sri Lanka     Namibia           8                     JJ Smit   
8    Namibia Vs Sri Lanka   Sri Lanka           1             Pathum Nissanka   
9    Namibia Vs Sri Lanka   Sri Lanka           2              Kusal Mendis†  
10   Namibia Vs Sri Lanka   Sri Lanka           3         Dhananjaya de Silva   
11   Namibia Vs Sri Lanka   Sri Lanka           4        Danushka Gunathilaka   
12   Namibia Vs Sri Lanka   Sri Lanka           5           Bhanuka Rajapaksa   
13   Namibia Vs Sri Lanka   Sri Lanka           6            Dasun Shanaka(c)   
14   Namibia Vs Sri Lanka   Sri Lanka           7  Wanindu Hasaranga de Silva   
15   Namibia Vs Sri Lanka   Sri Lanka           8         Chamika Karunaratne   
16   Namibia Vs Sri Lanka   Sri Lanka           9             Pramod Madushan   
17   Namibia Vs Sri Lanka   Sri Lanka          10         Dushmantha Chameera   
18   Namibia Vs Sri Lanka   Sri Lanka          11          Maheesh Theekshana   
19  U.A.E. Vs Netherlands      U.A.E.           1                 Chirag Suri   

    runs  
1      9  
2     20  
3     26  
4     20  
5     44  
6      0  
7     31  
8      9  
9      6  
10    12  
11     0  
12    20  
13    29  
14     4  
15     5  
16     0  
17     8  
18    11  
19    12

In [30]:
import numpy as np 

In [32]:
arr = np.array([1,2,3,4,5])
print("Array:", arr)

Array: [1 2 3 4 5]


### Addition ---->

In [35]:
add_arr = arr + 2
add_arr

array([3, 4, 5, 6, 7])

### Subtraction ---->

In [37]:
sub_arr = arr - 2
sub_arr

array([-1,  0,  1,  2,  3])

### Multiplication ---->

In [41]:
mul_arr = arr * 2
mul_arr

array([ 2,  4,  6,  8, 10])

### Division ---->

In [44]:
div_arr = arr / 2
div_arr

array([0.5, 1. , 1.5, 2. , 2.5])

### Indexing & Slicing ---->

In [47]:
element1 = arr[1]
element2 = arr[2]

print("Element_1:", element1)
print("Element_2:", element2)

slice = arr[2:4]
print("Slicing Array:", slice)

Element_1: 2
Element_2: 3
Slicing Array: [3 4]


### Reshaping Array ---->

In [50]:
reshape_arr = arr.reshape(5,1)
print(reshape_arr)

[[1]
 [2]
 [3]
 [4]
 [5]]


### Transposing Matrices ---->

In [55]:
transpose_arr = reshape_arr.T
print("Transposed Array: ", transpose_arr)

Transposed Array:  [[1 2 3 4 5]]


### Statistical Functions ---->

In [58]:
mean = np.mean(arr)
mean

3.0

In [60]:
median = np.median(arr)
median

3.0

In [62]:
std_dev = np.std(arr)
std_dev


1.4142135623730951

In [64]:
var = np.var(arr)
var

2.0

### Data Types In Arrays ---->

In [67]:
int_arr = np.array(arr, dtype=int)
print("Integer: ",int_arr)

Integer:  [1 2 3 4 5]


In [69]:
float_arr = np.array(arr, dtype=float)
print("float:",float_arr)

float: [1. 2. 3. 4. 5.]


In [71]:
bool_arr= np.array(arr, dtype=bool)
print("Boolean: ",bool_arr)

Boolean:  [ True  True  True  True  True]


In [73]:
str_arr = np.array(arr, dtype=str)
print("String: ",str_arr)

String:  ['1' '2' '3' '4' '5']


### Concatenating Array ---->

In [76]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print("Concatenated Array:", concatenated_arr)

Concatenated Array: [1 2 3 4 5 6]


### Sorting Arrays ---->

In [79]:
unsorted_array = np.array([3, 1, 2, 5, 4])
sorted_array_asc = np.sort(unsorted_array)  
sorted_array_desc = np.sort(unsorted_array)[::-1]  

print("Sorted Array (Ascending):", sorted_array_asc)
print("Sorted Array (Descending):", sorted_array_desc)

Sorted Array (Ascending): [1 2 3 4 5]
Sorted Array (Descending): [5 4 3 2 1]


### Assignments#9 Complete.....!!!